### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by uzabumuhire** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#13]
"NameError: name 'xrange' is not defined" in section "Dictionary Comprehensions" in "Appendix C - Python & Jupyter Notebook Tips". The following code  `a_dict = { k : k*k for k in xrange(10) }` should be changed to `a_dict = { k : k*k for k in range(10) }`

**Comment by ptwobrussell** [comment]
@uzabumuhire - Thanks for all of the thoughtful feedback! This is a good find. In Python 2, there was a `range` and a (more efficient for large collections) `xrange`. In Python 3, the API changed so that now there's just a `range` (which I believe is actually what the implementation of `xrange` used to be.) I'll update this in the appendix and then close out this ticket.
