### ISSUE TITLE
can't build it on windows 10 and linux 16.04

### ISSUE THREAD

**Issue by GSer** [mikhailklassen/Mining-the-Social-Web-3rd-Edition#2]
Error: 
> /opt/conda/bin/npm pack '@jupyter-widgets/jupyterlab-manager@^0.35'
jupyter-widgets-jupyterlab-manager-0.35.0.tgz

Errored, use --debug for full output:
ValueError:
"@jupyter-widgets/jupyterlab-manager@0.35.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=2.2.1 <3.0.0          >=1.1.0 <2.0.0   @jupyterlab/coreutils
>=0.19.2 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/notebook
>=0.19.1 <0.20.0        >=0.16.0 <0.17.0 @jupyterlab/rendermime
>=3.2.1 <4.0.0          >=2.0.0 <3.0.0   @jupyterlab/services

Proposed solution:
Instead of
jupyter labextension install @jupyter-widgets/jupyterlab-manager@^0.35 && \
jupyter labextension install jupyterlab_bokeh@^0.5.0 && \

use:
jupyter labextension install @jupyter-widgets/jupyterlab-manager && \
    jupyter labextension install jupyterlab_bokeh && \

**Comment by mikhailklassen** [comment]
Thanks for alerting me to this. I've removed the offending dependencies for now since I believe they were superfluous to the code anyway. Bokeh is not used anywhere in our codebase.
The Docker container should now build. We can add those dependencies back in later if we chose to convert some data visualizations to bokeh.

**Comment by mikhailklassen** [comment]
I'm going to close this issue for now.
